let riddles = 
[
    {url: "wordle_heb/index.html?word=0"},
    {url: "tiled_question/tiled_question.html?question=16"}, //image - person
    {url: "wordle_heb/index.html?word=1"},
    {url: "tiled_question/tiled_question.html?question=15"}, //image - location
    {url: "crossword/crossword.html?board=2"},
    {url: "tiled_question/tiled_question.html?question=2"}, //image - person
    {url: "wordle_heb/index.html?word=2"},
    {url: "tiled_question/tiled_question.html?question=1"}, //birthdays
    {url: "wordle_heb/index.html?word=3"},
    {url: "tiled_question/tiled_question.html?question=11"}, //image - location
    {url: "wordle_heb/index.html?word=13"},
    {url: "crossword/crossword.html?board=0"},
    {url: "wordle_heb/index.html?word=4"},
    {url: "tiled_question/tiled_question.html?question=6"}, //image - person
    {url: "wordle_heb/index.html?word=5"},
    {url: "tiled_question/tiled_question.html?question=13"}, //image - location
    {url: "wordle_heb/index.html?word=6"},
    {url: "tiled_question/tiled_question.html?question=7"}, //image - person
    {url: "crossword/crossword.html?board=1"},
    {url: "tiled_question/tiled_question.html?question=14"}, //image - location
    {url: "tiled_question/tiled_question.html?question=0"}, //flights
    {url: "wordle_heb/index.html?word=7"},
    {url: "tiled_question/tiled_question.html?question=4"}, //image - person
    {url: "crossword/crossword.html?board=3"},
    {url: "tiled_question/tiled_question.html?question=3"}, //image - person
    {url: "wordle_heb/index.html?word=12"},
    {url: "tiled_question/tiled_question.html?question=12"}, //image - location
    {url: "wordle_heb/index.html?word=8"},
    {url: "tiled_question/tiled_question.html?question=8"}, //image - person
    {url: "wordle_heb/index.html?word=9"},
    {url: "tiled_question/tiled_question.html?question=9"}, //image - location
    {url: "wordle_heb/index.html?word=10"},
    {url: "tiled_question/tiled_question.html?question=5"}, //image - person
    {url: "tiled_question/tiled_question.html?question=10"}, //image - location
    {url: "wordle_heb/index.html?word=11"},
    {url: "sudoku/sudoku.html?puzzle=0"},
]